name: Build, Lint, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-lint-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chidambaram27/nodejs-bk-demo:latest

      - name: Verify the image
        run: |
          docker pull chidambaram27/nodejs-bk-demo:latest
          docker run --rm chidambaram27/nodejs-bk-demo:latest node -v